<a href="https://colab.research.google.com/github/ProfAndersonVanin/IBM3130-PLN-2026/blob/main/semana-04/Aula04_Calculo_Esparsidade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CÁLCULO DE ESPARSIDADE - MATRIZ BoW**



```
Bag of Words Vetores:
[0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1]
[1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1]
[0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1]
```



In [12]:
# Corpus
corpus = [
    "código Python funciona bem",
    "código Java rápido",
    "Python e Java"
]

In [16]:
# Importar bibliotecas e recursos
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [17]:
# Criar lista vazia para guardar todas as palavras do corpus
todas_palavras=[]

In [18]:
# Processar cada frase da lista separadamente e converter para minusculo
for frase in corpus:
  palavras_frase = word_tokenize(frase.lower())
  todas_palavras.extend(palavras_frase)

In [19]:
todas_palavras

['código',
 'python',
 'funciona',
 'bem',
 'código',
 'java',
 'rápido',
 'python',
 'e',
 'java']

In [20]:
# Extrair vocabulário único (sem repetições)
vocabulario = sorted(set(todas_palavras))
vocabulario

['bem', 'código', 'e', 'funciona', 'java', 'python', 'rápido']

In [21]:
# Obter e guadar tamanho do vocabulário
tam_vocab = len(vocabulario)
tam_vocab

7

In [22]:
# Obter a quantidade de documentos do corpus
qtd_documentos = len(corpus)
qtd_documentos

3

In [23]:
# Calcular total de posições da matriz com o vocabulario
total_posicoes = qtd_documentos * tam_vocab
total_posicoes

21

In [26]:
# Montar a matriz BoW
matriz_bow = []
for frase in corpus:
  palavras_frase = word_tokenize(frase.lower())
  vetor_frase = [palavras_frase.count(palavra) for palavra in vocabulario]
  matriz_bow.append(vetor_frase)

In [27]:
matriz_bow

[[1, 1, 0, 1, 0, 1, 0], [0, 1, 0, 0, 1, 0, 1], [0, 0, 1, 0, 1, 1, 0]]

In [ ]:
# Criar os vetores de frequencia para cada frase (documento) com base no vocabulario

In [28]:
# visualizar os resultados
print("Vocabulario==> ",vocabulario)
for i, linha in enumerate(matriz_bow):
  print(f"Documento {i+1}: {linha} -> ({corpus[i]})")

Vocabulario==>  ['bem', 'código', 'e', 'funciona', 'java', 'python', 'rápido']
Documento 1: [1, 1, 0, 1, 0, 1, 0] -> (código Python funciona bem)
Documento 2: [0, 1, 0, 0, 1, 0, 1] -> (código Java rápido)
Documento 3: [0, 0, 1, 0, 1, 1, 0] -> (Python e Java)


In [29]:
# Converter a lista para numpy array
import numpy as np
matriz_np = np.array(matriz_bow)
matriz_np

array([[1, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 1, 0]])

In [30]:
total_zeros = np.sum(matriz_np == 0)
total_zeros

np.int64(11)

In [34]:
# Calcular a Esparsidade (%)
esparsidade = total_zeros / total_posicoes
print(f"Esparsidade = {esparsidade*100:.2f}%")

Esparsidade = 52.38%


In [39]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    "código Python funciona bem",
    "código Java rápido",
    "Python e Java"
]
# Cria um Objeto CountVectorizer
vectorizer = CountVectorizer()
# Treina e transforma o corpus
X = vectorizer.fit_transform(corpus)
# Imprime o vocabulário gerado
print("Vocabulario:", vectorizer.get_feature_names_out())
# Imprime a matriz Bag-of-Words
print("BoW Representação:")
print(X.toarray())

Vocabulario: ['bem' 'código' 'funciona' 'java' 'python' 'rápido']
BoW Representação:
[[1 1 1 0 1 0]
 [0 1 0 1 0 1]
 [0 0 0 1 1 0]]


In [37]:
vectorizer.get_feature_names_out()

array(['bem', 'código', 'funciona', 'java', 'python', 'rápido'],
      dtype=object)

In [38]:
vectorizer.vocabulary_

{'código': 1, 'python': 4, 'funciona': 2, 'bem': 0, 'java': 3, 'rápido': 5}

In [4]:
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 9 stored elements and shape (3, 6)>